spring:
  main:
    allow-bean-definition-overriding : true
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/scul} # jdbc:mysql://mysql.xquare.app:3306/prod_scul
    username: ${DB_USERNAME:root} # xquare-scul
    password: ${DB_PASSWORD:070211} # WVMwMKB2gGWE
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        defer-datasource-initialization: true
  data:
    redis:
      host: redis.xquare.app
      port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  header: ${HEADER:Authorization}
  prefix : ${PREFIX:Bearer}
  secret-key: ${JWT_SECRET_KEY:dfhasjkdddddddddddddddddddddddfhayffhdtyhdhydshghjkdfaskverafter}
  access-exp: ${JWT_ACCESS_EXP:10000}
  refresh-exp: ${JWT_REFRESH_EXP:604800}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:a}
      secret-key: ${AWS_SECRET_KEY:a}
    s3:
      bucket: kangsunbucket
    region:
      static: ap-northeast-2

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error